RUNID: "Sample analysis"
REFIDS: ["GRCh37","GRCh38-GIABv3", "CHM13V2"]
REF:
  GRCh37: resources/hs37d5.fa.gz
  GRCh38-GIABv3: resources/GRCh38_GIABv3_no_alt_analysis_set_maskedGRC_decoys_MAP2K3_KMT2C_KCNJ18.fasta.gz
  CHM13V2: resources/chm13v2.0.fa
SAMPLES:
  [
  sample1
  ]
THREADS:
  bwa: 22
  samsort: 12
  samstat: 4
MEMORY: "128"
READPAIRS:
  sample1:
    read_group:
    R1: test_dataset/sample1_R1.fastq.gz
    R2: test_dataset/sample2_R2.fastq.gz
